### PR TITLE
feat: Pass PR number to the getPullChanges

### PR DESCRIPTION
**Pull request by mihaerzen**
Hi all 👋

In our CI, we are running our job on every push. This means we are relying on passing the PR number via `pr-number` variable. I have noticed, this was not respected in the `getPullChanges` method, so I added it. I also added some tests for the functionality added. Let me know if I missed something obvious!

Thank you 🤝

### CODE REVIEW

**Comment by mihaerzen** [comment]
@davelosert Any chance I can get this reviewed?

**Review by davelosert — APPROVED** [review]
@mihaerzen : Great catch and thank you very for this, great work!

I just reverted the `/dist` files as they are actually rebuild during the release process - besides that, I will merge it as it is (I am currently in a major refactoring for this, so I will do some minor changes myself during that).

**Comment by mihaerzen** [comment]
@davelosert Perfect! Yeah I was unsure about the `dist` part. Thanks 🤝

**Comment by mihaerzen** [comment]
Amazing, this works already! Thank you @davelosert

**Pull request merged**
